package com.eventhub.common.error;

import org.springframework.http.HttpStatus;

public enum ErrorCode {
    VALIDATION_ERROR("VALIDATION_ERROR", "请求参数校验失败", HttpStatus.BAD_REQUEST),
    CONFLICT("CONFLICT", "数据已存在", HttpStatus.CONFLICT),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS", "账号或密码错误", HttpStatus.UNAUTHORIZED),
    AUTH_ACCOUNT_DISABLED("AUTH_ACCOUNT_DISABLED", "账号不可用", HttpStatus.FORBIDDEN),
    AUTH_CLIENT_NOT_ALLOWED("AUTH_CLIENT_NOT_ALLOWED", "当前账号不能登录该客户端", HttpStatus.FORBIDDEN),
    AUTH_REFRESH_INVALID("AUTH_REFRESH_INVALID", "登录状态已失效，请重新登录", HttpStatus.UNAUTHORIZED),
    AUTH_CSRF_INVALID("AUTH_CSRF_INVALID", "安全校验失败，请重新登录", HttpStatus.FORBIDDEN),
    AUTH_LOGIN_LOCKED("AUTH_LOGIN_LOCKED", "登录失败次数过多，请稍后再试", HttpStatus.TOO_MANY_REQUESTS),
    AUTH_UNAUTHORIZED("AUTH_UNAUTHORIZED", "请先登录", HttpStatus.UNAUTHORIZED),
    AUTH_FORBIDDEN("AUTH_FORBIDDEN", "无权访问该资源", HttpStatus.FORBIDDEN),
    MERCHANT_NOT_BOUND("MERCHANT_NOT_BOUND", "当前账号未绑定商家", HttpStatus.FORBIDDEN),
    MERCHANT_INACTIVE("MERCHANT_INACTIVE", "商家或员工账号不可用", HttpStatus.FORBIDDEN),
    VENUE_NOT_FOUND("VENUE_NOT_FOUND", "场馆不存在", HttpStatus.NOT_FOUND),
    VENUE_ACCESS_DENIED("VENUE_ACCESS_DENIED", "无权操作该场馆", HttpStatus.FORBIDDEN),
    ACTIVITY_NOT_FOUND("ACTIVITY_NOT_FOUND", "活动不存在", HttpStatus.NOT_FOUND),
    ACTIVITY_ACCESS_DENIED("ACTIVITY_ACCESS_DENIED", "无权操作该活动", HttpStatus.FORBIDDEN),
    ACTIVITY_STATUS_INVALID("ACTIVITY_STATUS_INVALID", "当前活动状态不允许该操作", HttpStatus.CONFLICT),
    ACTIVITY_INCOMPLETE("ACTIVITY_INCOMPLETE", "活动信息不完整，暂不能提交审核", HttpStatus.BAD_REQUEST),
    ACTIVITY_VERSION_CONFLICT("ACTIVITY_VERSION_CONFLICT", "活动已被其他操作更新，请刷新后重试", HttpStatus.CONFLICT),
    ACTIVITY_NOT_AVAILABLE("ACTIVITY_NOT_AVAILABLE", "活动暂不可查看", HttpStatus.NOT_FOUND),
    ACTIVITY_FAVORITE_NOT_FOUND("ACTIVITY_FAVORITE_NOT_FOUND", "收藏记录不存在", HttpStatus.NOT_FOUND),
    ACTIVITY_REVIEW_NOT_FOUND("ACTIVITY_REVIEW_NOT_FOUND", "评价不存在", HttpStatus.NOT_FOUND),
    ACTIVITY_REVIEW_NOT_ELIGIBLE("ACTIVITY_REVIEW_NOT_ELIGIBLE", "仅已购票且场次开始后的用户可以评价", HttpStatus.FORBIDDEN),
    ACTIVITY_REVIEW_HIDDEN("ACTIVITY_REVIEW_HIDDEN", "该评价已被平台隐藏", HttpStatus.CONFLICT),
    SESSION_TIME_INVALID("SESSION_TIME_INVALID", "场次或售票时间设置不正确", HttpStatus.BAD_REQUEST),
    TICKET_TYPE_INVALID("TICKET_TYPE_INVALID", "票档设置不正确", HttpStatus.BAD_REQUEST),
    SESSION_NOT_AVAILABLE("SESSION_NOT_AVAILABLE", "当前场次不可售", HttpStatus.CONFLICT),
    SEAT_NOT_FOUND("SEAT_NOT_FOUND", "座位不存在", HttpStatus.NOT_FOUND),
    SEAT_NOT_AVAILABLE("SEAT_NOT_AVAILABLE", "座位不可售", HttpStatus.CONFLICT),
    SEAT_ALREADY_LOCKED("SEAT_ALREADY_LOCKED", "座位已被其他用户锁定", HttpStatus.CONFLICT),
    SEAT_LOCK_NOT_FOUND("SEAT_LOCK_NOT_FOUND", "座位锁定不存在", HttpStatus.NOT_FOUND),
    SEAT_LOCK_EXPIRED("SEAT_LOCK_EXPIRED", "座位锁定已过期", HttpStatus.CONFLICT),
    SEAT_LOCK_ACCESS_DENIED("SEAT_LOCK_ACCESS_DENIED", "无权操作该座位锁定", HttpStatus.FORBIDDEN),
    STOCK_NOT_ENOUGH("STOCK_NOT_ENOUGH", "可售库存不足", HttpStatus.CONFLICT),
    PURCHASE_LIMIT_EXCEEDED("PURCHASE_LIMIT_EXCEEDED", "超过单次限购数量", HttpStatus.BAD_REQUEST),
    IDEMPOTENCY_KEY_REQUIRED("IDEMPOTENCY_KEY_REQUIRED", "缺少有效的幂等键", HttpStatus.BAD_REQUEST),
    IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT", "幂等键已用于其他请求", HttpStatus.CONFLICT),
    ORDER_NOT_FOUND("ORDER_NOT_FOUND", "订单不存在", HttpStatus.NOT_FOUND),
    ORDER_ACCESS_DENIED("ORDER_ACCESS_DENIED", "无权访问该订单", HttpStatus.FORBIDDEN),
    ORDER_STATUS_INVALID("ORDER_STATUS_INVALID", "当前订单状态不允许该操作", HttpStatus.CONFLICT),
    ORDER_PAYMENT_EXPIRED("ORDER_PAYMENT_EXPIRED", "订单支付时间已过", HttpStatus.CONFLICT),
    PAYMENT_ALREADY_COMPLETED("PAYMENT_ALREADY_COMPLETED", "订单已支付", HttpStatus.CONFLICT),
    TICKET_NOT_FOUND("TICKET_NOT_FOUND", "票券不存在", HttpStatus.NOT_FOUND),
    TICKET_ACCESS_DENIED("TICKET_ACCESS_DENIED", "无权访问该票券", HttpStatus.FORBIDDEN),
    TICKET_ALREADY_USED("TICKET_ALREADY_USED", "票券已核销", HttpStatus.CONFLICT),
    TICKET_STATUS_INVALID("TICKET_STATUS_INVALID", "当前票券状态不允许该操作", HttpStatus.CONFLICT),
    TICKET_CREDENTIAL_INVALID("TICKET_CREDENTIAL_INVALID", "票券凭证无效", HttpStatus.BAD_REQUEST),
    TICKET_CREDENTIAL_EXPIRED("TICKET_CREDENTIAL_EXPIRED", "票券凭证已过期", HttpStatus.BAD_REQUEST),
    TICKET_MERCHANT_MISMATCH("TICKET_MERCHANT_MISMATCH", "该票券不属于当前商家", HttpStatus.FORBIDDEN),
    NOTIFICATION_NOT_FOUND("NOTIFICATION_NOT_FOUND", "通知不存在", HttpStatus.NOT_FOUND),
    AI_NOT_CONFIGURED("AI_NOT_CONFIGURED", "AI 助手尚未配置", HttpStatus.SERVICE_UNAVAILABLE),
    AI_CONVERSATION_NOT_FOUND("AI_CONVERSATION_NOT_FOUND", "AI 会话不存在", HttpStatus.NOT_FOUND),
    AI_CONVERSATION_ACCESS_DENIED("AI_CONVERSATION_ACCESS_DENIED", "无权访问该 AI 会话", HttpStatus.FORBIDDEN),
    AI_STREAM_BUSY("AI_STREAM_BUSY", "当前已有 AI 回复正在生成", HttpStatus.CONFLICT),
    AI_UPSTREAM_UNAVAILABLE("AI_UPSTREAM_UNAVAILABLE", "AI 服务暂时不可用", HttpStatus.BAD_GATEWAY),
    AI_TOOL_LIMIT_EXCEEDED("AI_TOOL_LIMIT_EXCEEDED", "AI 工具调用次数过多", HttpStatus.BAD_GATEWAY),
    MEDIA_INVALID_IMAGE("MEDIA_INVALID_IMAGE", "仅支持有效的 JPG 或 PNG 图片", HttpStatus.BAD_REQUEST),
    MEDIA_FILE_TOO_LARGE("MEDIA_FILE_TOO_LARGE", "图片不能超过 5 MB", HttpStatus.PAYLOAD_TOO_LARGE),
    MEDIA_STORAGE_FAILED("MEDIA_STORAGE_FAILED", "图片保存失败，请稍后重试", HttpStatus.INTERNAL_SERVER_ERROR),
    MEDIA_NOT_FOUND("MEDIA_NOT_FOUND", "图片不存在", HttpStatus.NOT_FOUND),
    METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED", "不支持当前请求方法", HttpStatus.METHOD_NOT_ALLOWED),
    INTERNAL_ERROR("INTERNAL_ERROR", "服务器发生异常", HttpStatus.INTERNAL_SERVER_ERROR);

    private final String code;
    private final String message;
    private final HttpStatus status;

    ErrorCode(String code, String message, HttpStatus status) {
        this.code = code;
        this.message = message;
        this.status = status;
    }

    public String code() {
        return code;
    }

    public String message() {
        return message;
    }

    public HttpStatus status() {
        return status;
    }
}
